{{- if .Values.bridge.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "brain-swarm.fullname" . }}-ing
  annotations:
    kubernetes.io/ingress.class: {{ .Values.bridge.ingress.className }}
{{- if .Values.bridge.ingress.annotations }}
{{ toYaml .Values.bridge.ingress.annotations | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts: [ {{ .Values.bridge.ingress.host | quote }} ]
      secretName: {{ .Values.bridge.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.bridge.ingress.host }}
      http:
        paths:
          - path: /gh-webhook
            pathType: Prefix
            backend:
              service:
                name: {{ include "brain-swarm.fullname" . }}-bridge
                port: { number: 80 }
          - path: /jira-webhook
            pathType: Prefix
            backend:
              service:
                name: {{ include "brain-swarm.fullname" . }}-bridge
                port: { number: 80 }
          - path: /servicenow-webhook
            pathType: Prefix
            backend:
              service:
                name: {{ include "brain-swarm.fullname" . }}-bridge
                port: { number: 80 }
{{- end }}