{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "brain-swarm.fullname" . }}-sm
spec:
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app: cortex
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "brain-swarm.fullname" . }}-bridge-sm
spec:
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app: bridge
{{- end }}