{{- if .Values.monitoring.alertmanager.enabled }}
{{- if .Values.monitoring.alertmanager.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "brain-swarm.fullname" . }}-swarmops-hook-kilo
  labels:
    {{- include "brain-swarm.labels" . | nindent 4 }}
    app.kubernetes.io/component: swarmops-hook-kilo
spec:
  type: {{ .Values.monitoring.alertmanager.webhook.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.monitoring.alertmanager.webhook.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.monitoring.alertmanager.webhook.service.type "NodePort") .Values.monitoring.alertmanager.webhook.service.nodePort }}
      nodePort: {{ .Values.monitoring.alertmanager.webhook.service.nodePort }}
      {{- end }}
  selector:
    {{- include "brain-swarm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: swarmops-hook-kilo
{{- end }}
{{- end }}