apiVersion: v1
kind: Secret
metadata:
  name: {{ include "local-admin.fullname" . }}-secret
  labels:
    {{- include "local-admin.labels" . | nindent 4 }}
type: Opaque
data:
  jwt_secret: {{ .Values.jwtSecret | quote }}